### PR TITLE
Fix Item Editor

### PR DESCRIPTION
**Pull request by Chrisnetika**
Updated quest_template sql queries so it finds proper columns

### CODE REVIEW

**Comment by Chrisnetika** [comment]
my 1st git pull request .. idk how readme got involved but the other file is good

**Comment by Chrisnetika** [comment]
had to revert login.php to earlier commit without captcha because the login form wont show

**Comment by Amit86** [comment]
can you post the errors you got with the login page so we can fix them?

**Comment by Chrisnetika** [comment]
Parse error: syntax error, unexpected '>' in C:\WampDeveloper\Websites\wowserver.local\webroot\tcman\login.php on line 133 
that is error I get with login.php .. with or without captcha on, im trying to fix it as well.... but it just one those things that baffle me lol

**Comment by Amit86** [comment]
im almost sure it should work now, please give it a try (pushed a fix)

**Pull request merged**
