### PR TITLE
Fixed Character's Quest Viewer

### PR DESCRIPTION
**Pull request by Chrisnetika**
incorrect sql query fixed... may need more rework regarding quest status/rewarded

### CODE REVIEW

**Comment by Chrisnetika** [comment]
since quest rewarded status is in a different table.. it wont properly show rewarded quests but it will show current quests.To show rewarded quests would need an inner join to character_quest_rewarded

**Comment by Amit86** [comment]
mind doing the inner join before i merge?

btw, i fixed the login.php problems

**Comment by Chrisnetika** [comment]
actually it be a Left Join on line 74 .. I tried but I cant get it to work .. im not so well with joining .. rewarded needs to point to character_queststatus_rewarded.quest and be selected
Ill try to build query in navicat tho and see what I can come with

**Comment by Chrisnetika** [comment]
closest I can get is this
SELECT a.quest, a.status FROM character_queststatus a LEFT JOIN character_queststatus_rewarded b ON a.guid = b.guid Where a.guid = '.$id.' AND (a.status = 3 OR a.status = 1) ORDER BY status DESC

I can't get the quest column in rewarded table to appear as rewarded in query :/

**Comment by Chrisnetika** [comment]
I managed to make a join
            $result = $sqlc->query('SELECT a.quest, a.status, b.quest AS rewarded FROM character_queststatus a LEFT JOIN character_queststatus_rewarded b ON a.guid = b.guid WHERE a.guid = '.$id.' AND ( a.status = 3 OR a.status = 1 ) ORDER BY a.status DESC');
only issue is...it not displaying right but I think I know why.. before rewarded was a separate table I think it was just a flag but now it just lists quests which in turn messes this function :/

**Comment by Amit86** [comment]
i think this page needs to be rewritten to show all quest tables each one as a table since we also have daily + weekly + seasonal which are currently not taken into account at all

**Comment by Chrisnetika** [comment]
my pull request is good for now.. it just cant show if quest was rewarded or not .. it take a rewrite of that fucntion to support the seperate table

**Pull request merged**
